export const SET_PAGE_USERS = 'DATA/SET_PAGE_USERS';
export const SET_PAGE_USERS_TO_SHOW = 'DATA/SET_PAGE_USERS_TO_SHOW';
export const ADD_SUBSCRIPTION = 'DATA/ADD_SUBSCRIPTION';
export const REMOVE_SUBSCRIPTION = 'DATA/REMOVE_SUBSCRIPTION';
export const SHOW_PRELOADER = 'DATA/SHOW_PRELOADER';
export const HIDE_PRELOADER = 'DATA/HIDE_PRELOADER'; 